# Basic Python

## 1. Split this string

In [9]:
s = "Hi there Sam!"

In [10]:
s.split()


['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [16]:

print("the diameter of Earth is {} kilometers".format(diameter))


the diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [17]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [18]:
data=d
d=data['k1']
for x in d:
  x
data1=x
x=data1['tricky']
for y in x:
  y
data2=y
y=data2['target']
print(y[3])  



hello


# Numpy

In [20]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [30]:
x= np.zeros((2,5))
n=np.ones((2,5))*5

In [69]:
print(x)
print(n)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


## 5. Create an array of all the even integers from 20 to 35

In [44]:
d=np.arange(20,35,2)
print(d)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [33]:
a=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [42]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)



[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [45]:
import pandas as pd


In [55]:
dat=[12,13]
c=pd.DataFrame(dat)
print(c)

    0
0  12
1  13


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [58]:
s=pd.date_range(start='01/01/2023',end='10/02/2023')
print(s)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [63]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [66]:
m=pd.DataFrame(lists,columns=['s.no','name','rollno'])
print(m)

   s.no name  rollno
0     1  aaa      22
1     2  bbb      25
2     3  ccc      24
